version: "3"
services:
  redis:
    image: redis:alpine
    hostname: redis
    ports:
      - 6379:6379
    environment:
        - REDIS_MASTER_HOST=127.0.0.1
  employee-sv:
    image: employee:1.0
    container_name: employee-sv
    ports:
     - 9090:8080
    links:
      - redis